stages:
  - build
  - deploy

build:
  image: node:14.15.5
  artifacts:
    paths:
      - dist/*
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run ng build --prod


deploy_staging:
  stage: deploy
  image: kroniak/ssh-client
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "${SSH_PRIVATE_KEY_PRODUCTION}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh ${PRODUCTION_HOST} rm -rf /usr/share/nginx/crm/*
    - scp -r dist/vex/* ${PRODUCTION_HOST}:/usr/share/nginx/crm
    - ssh ${PRODUCTION_HOST} systemctl restart nginx
    - sleep 15
